### ISSUE TITLE
can't run baseline_rl.py

### ISSUE THREAD

**Issue by cihantugrulcicek** [paulorocosta/ai-for-tsp-competition#1]
I wasn't able to run the `baseline_rl.py`. When I run the code with `from_file=True`, and providing `x_dir` and `adj_dir`,
- First, I got a `file not found error` for the adj file. I guess this occurs as adj files start with `adj-` in the validation set. However, this is not specified in `batch_env_rl`. 
- Even though I rename the adj file with the same name of the x file, I got the following error on line 44 of 'batch_env_rl', 
'ValueError: could not broadcast input array from shape (20,3) into shape (50,3)', which seems that the number of nodes are not read from file, instead, read `n_nodes` argument in the constructor. 
- After passing 'n_nodes' argument with 'from_file=True', I still got the error `Sizes of tensors must match except in dimension 1. Got 32 and 1 in dimension 0 (The offending index is 1)` on line 54 in 'train_baseline.py'.

**Comment by paulorocosta** [comment]
Hi @cihantugrulcicek , 
The ``baseline_rl.py`` will not work if you call it ``from_file=True``. It's made to generate instances on the fly. If you want to call it from a file you will need to adapt `` batch_env_rl.py`` to read the files.

**Comment by paulorocosta** [comment]
Hi @cihantugrulcicek, 
Thanks for bringing this to our attention. 
I have updated the code to read ``from_file=True`` when using the ``batch_env_rl``.
An example of how you can call it can be found below. Note that when reading files with a different number of nodes, the instance features are padded with zeros when the number of nodes is smaller than the maximum number of nodes in the files. 

```python 
    import os
    base_dir = os.path.dirname(os.getcwd())
    x_dir = os.path.join(base_dir, 'data', 'valid', 'instances')
    adj_dir = os.path.join(base_dir, 'data', 'valid', 'adjs')
    batch_env = BatchEnvRL(n_envs=2, from_file=True, x_dir=x_dir, adj_dir=adj_dir)
```
Please let me know if this is working now. 

Thanks again for your feedback!

**Comment by cihantugrulcicek** [comment]
it works now.. thank you for quick respond

**Comment by cihantugrulcicek** [comment]
Dear Paulo,

Thanks for fixing the issue very quickly. I'd like to ask another question
related to problem definition. When running the code, if we decide to visit
a particular node in an instance and the tour time exceeds the closing time
of this node at the time of visit, i.e. after random noise is added,
'self.feas' variable is immediately set to 'False', and there is no way to
set it back to 'True', i.e., decision causes an infeasibility for the
instance. Is this due to problem definition? Imho, the only infeasibility
occurs if the tour time exceeds the maximum tour length, i.e. self.maxT,
because, even though a particular node doesn't yield a reward when visited
after its closing time, another node which would be visited after
traversing this particular node would still have a chance to yield reward
unless the maximum tour length is not exceeded. I'd appreciate it if you
clarify this issue for me. Thanks again.

Cihan

Paulo da Costa ***@***.***>, 14 May 2021 Cum, 14:12 tarihinde
şunu yazdı:

**Comment by paulorocosta** [comment]
Hi @cihantugrulcicek,

Yes, our interpretation is that if you violate one of the time windows from above (you can still be early without any penalty) we deem the solution 'infeasible'. 
This is also true for when you exceed ``maxT``. 
Note that if you only exceed the time windows a couple of times there is still a chance you can get a 'good' tour out of it even though it's 'infeasible'.
I hope this clarifies the matter.

Cheers, 

Paulo
